name: 'megaworkflow' 
on:
  push

jobs: 
  superstar:
    name: 'SuperJob'
    runs-on: 'ubuntu-latest'
    defaults: 
      run:
        shell: bash
    steps:
    - name: ping google.com
      run: ping -c 3 8.8.8.8 || true


