name: 'Rebel Workflow' 
on:
  workflow_run:
    workflows: ["Demo Workflow"] # using this we can restrict the job on workflow level this will run after 
    branches: [master]           # finishing the Demo workflow 
    types:
      - completed 

jobs: 
  superstar:
    name: 'SuperJob'
    runs-on: 'ubuntu-latest'
    defaults: 
      run:
        shell: bash
    steps:
    - name: ping google.com
      run: ping -c 3 8.8.8.8 || true
