name: 'Rebel Workflow' 
on:
  workflow_run:
    workflows: ["Demo Workflow"]
    branches: [master]
    types:
      - completed 

jobs: 
  superstar:
    name: 'SuperJob'
    runs-on: 'ubuntu-latest'
    defaults: 
      run:
        shell: bash
    steps:
    - name: ping google.com
      run: ping -c 3 8.8.8.8 || true
