# This is demo workflow file to test github actions

# notes

# name = Display name of the job
# 'on' = useful to trigger pipeline , on what event build should trigger eg : push , pull
# for reference https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# we can use cron schedule in 'on option'

name: 'Demo work flow' 
on:
  push

jobs: 
  superstar:
    name: 'SuperJob'
    runs-on: 'ubuntu-latest'
    defaults: 
      run:
        shell: bash
    steps:
    - name: ping google.com
      run: ping -c 3 8.8.8.8 || true

  megastar:
    name: 'MegaJob'
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
    - name: checking pwd
      run: pwd 

  rebelstar:
    name: 'RebelJob'
    runs-on: "ubuntu-latest"
    needs: megastar
    defaults:
      run:
        shell: bash
    steps:
    - name: Install groovy
      run: sudo apt-get update && sudo apt-get install -y groovy
    - name: Execute Groovy Script
      run: |               # Here, the "|" symbol is used in GitHub Actions for multiline code
        echo 'println "Hello, Groovy!"' > script.groovy
        groovy script.groovy

